[project]
name = "ester-mastal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Masatoshi Ono", email = "m-ono@resys.jp" }
]
requires-python = ">=3.13"
dependencies = [
    "pyxel>=2.9.8",
]

[project.scripts]
ester-mastal = "ester_mastal:main"
test = "ester_mastal:test_cli"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "numpy>=2.5.2",
    "pillow>=12.3.0",
    "ruff>=0.16.1",
]
