@startuml 状態遷移図

[*] -> フィールドシーン

state フィールドシーン {
    [*] --> 探索モード
    探索モード : 十字キーで移動できる
    探索モード --> 探索モード
    探索モード --> メニューモード : メニューボタン押下
    メニューモード --> 探索モード : メニューキャンセル
    探索モード --> 調査モード : 眼の前を調べる
    調査モード --> 探索モード : それぞれの状態が終わり

    state 調査モード {
        state c <<choice>>
        [*] --> c
        c --> お店 : お店だったら
        c --> 宿屋 : 宿屋だったら
        c --> 宝箱 : 宝箱だったら
        c --> 会話 : 人だったら
        c --> ボス会話 : ラスボスだったら
    }
}

探索モード --> 戦闘シーン : 敵と遭遇
ボス会話 --> 戦闘シーン : ボス会話終了
戦闘シーン --> 探索モード : 勝利 / にげる成功

state 戦闘シーン {
}

戦闘シーン --> ゲームオーバー : 戦闘に敗北
戦闘シーン --> エンディング : ラスボスに勝利

ゲームオーバー --> [*]
エンディング --> [*]

@enduml